apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello-app
resources:
  - ../app
images:
- name: gcr.io/google-samples/hello-app
  newTag: "2.0"
patches:
  - path: service.yaml
    target:
      kind: Service
