apiVersion: v1
kind: Service
metadata:
  name: hello-app
  namespace: hello-app
spec:
  type: NodePort
  selector:
    app: hello-app
  ports:
    - name: http 
      port: 8080
      nodePort: 30001
